### PR TITLE
Move to GitHub actions for checks and release

### PR DESCRIPTION
**Pull request by gtrog**
This PR is a major overhaul of how versioning and releasing to NuGet will work from now on as well as pull request checks.  Here are all the changes:
- Removing usage of Travis CI, I want to start using GitHub actions for all CI related things
- Added `pull_request.yml` GitHub action workflow for pull request checks which will build the project and run unit tests
- Added `release.yml` GitHub action workflow that will trigger a release build and publish to NuGet any time a GitHub Release is published, and, will use the version of the release tag to generate the assembly version and NuGet package version
- I've removed all copyright notices, since Application Security, Inc. no longer exists
- Added `.nuspec` file for building and publishing NuGet package
- Switched to newer log4net version and moved it to use NuGet
- Fixed unit tests which failed because they were not setting `TypeFilterLevel.Full`, which prevents serialization/deserialization of some times
- Fixed unit test that sets process priority, which can't be set to `RealTime` unless running as an admin

### CODE REVIEW

**Comment by vivekrathod** [comment]
I sense you giving some much needed TLC to this project :)

**Comment by gtrog** [comment]
> I sense you giving some much needed TLC to this project :)

Not an easy feat when you haven't done .NET in almost a decade and a lot of breaking changes have cropped up with time 😬

**Comment by gtrog** [comment]
@vivekrathod All ready for review

**Review by vivekrathod — APPROVED** [review]
great job (Y)

**Pull request merged**
