### PR TITLE
adding global assembly info

### PR DESCRIPTION
**Pull request by vivekrathod**

### CODE REVIEW

**Comment by gtrog** [comment]
Sweet! Travis CI passed building the solution using Mono.  Not a full coverage solution but better than nothing for being free.

**Comment by vivekrathod** [comment]
awesome :) does it run tests as well?

**Comment by gtrog** [comment]
No, there's probably a way to add it to the .travis.yml file.  We could add a build.sh file that takes care of building the solution and running the tests and point .travis.yml at it.  This runs on a linux environment, so who knows what the limitations may be, it's at least good to know if the build itself is broken.

**Comment by gtrog** [comment]
More information: http://docs.travis-ci.com/user/languages/csharp/

**Comment by vivekrathod** [comment]
yes def - btw I've been having problems with auto restoring the
NUnit.Runner package in my env - NUnit.Framework and log4net seem ok - will
update later with what I find

**Pull request merged**
