### PR TITLE
Add empty src/Version directory required by default build process

### PR DESCRIPTION
**Pull request by gtrog**
Would this fix it?

It adds a .gitignore file that tells it to ignore everything in this directory, except itself, that way the directory will get commited even though it may be empty

### CODE REVIEW

**Comment by vivekrathod** [comment]
yeah looks like this should fix it

**Comment by gtrog** [comment]
Let me rebase this PR, I'm also trying to get Travis CI to work, which will allow us to know if a PR breaks a build

**Comment by gtrog** [comment]
So in order to get Travis CI to work, I can't use build.cmd, since it's using Mono to build the solution.  This means that the GlobalAssemly.cs file won't be generated.  Can you remember any reason why we couldn't just commit that file as well, even though it'll get regenerated/updated with each version increment (which is no big deal)

**Comment by vivekrathod** [comment]
I think it should be OK to just overwrite it each time..

**Comment by gtrog** [comment]
Can you add a pull request for it? I don't have a Visual Studio environment

**Comment by vivekrathod** [comment]
sure

**Pull request merged**
